name: Node.js CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Running-on-test-env:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Printing first message
      run: echo "This step only runs on dev env, and requires code review"
