name: Node.js CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Printing first message
      run: echo "This step only runs on the main branch"
